### ISSUE TITLE
Tarea para configurar todo el ambiente de rankmi

### ISSUE THREAD

**Issue by xleninx** [Rankmi/alfred#53]
- [ ] rvm

- [ ] ruby 2.3.7

- [ ] rails

- [ ] nvm

- [ ] node 10

- [ ] redis

- [ ] mongo

- [ ] postgres 9.6

- [ ] archivo host

- [ ] repo api (bundle install, migrations, etc)

- [ ] repo app (npm i)

- [ ] repo api-translations (npm i)

- [ ] repo rankmi-admin (npm i)

**Comment by jesujcastillom** [comment]
@xleninx Node debe ser al menos la versión 10
